/**
 * Content registry — lazy edition.
 *
 * The old registry imported every lesson/kernel eagerly, which pushed the
 * whole course (~2.4 MB) into the first-load bundle. This edition keeps the
 * same conceptual model ("content is data") but loads subject chunks on
 * demand:
 *
 * - `src/content/lesson-index.generated.ts` holds a tiny statically-known
 *   index (title/summary/syllabus ids) for pages that only need metadata
 *   (home coverage map, vocab, hooks). It is generated by
 *   `scripts/gen-lesson-index.ts` — run `pnpm gen:index` after content edits.
 * - Full lesson bodies + kernels load per subject via dynamic import;
 *   `vite.config.ts` groups them into one chunk per subject (`content-0625`…).
 * - Standalone question banks (`src/content/questions/*.ts`) follow the same
 *   pattern, ready for the Paper-style bank work.
 *
 * Promises are cached so React `use()` gets a stable reference per subject.
 */

import type { Lesson, SimKernel, Question } from '@/content/types'
import { LESSON_INDEX } from '@/content/lesson-index.generated'
import type { LessonMeta } from '@/lib/lessonMeta'
import { SYLLABUS_META } from '@/content/syllabus/meta.generated'
import { loadSyllabus } from '@/content/syllabus'

export type { Lesson, SimKernel, Question, LessonMeta }
export { SYLLABUS_META, loadSyllabus }

/* ------------------------------------------------------------------ *
 * Lazy module tables. Vite turns each entry into a dynamic import;
 * manualChunks then folds the per-file chunks into one chunk per
 * subject, so loading any lesson of a subject costs exactly one
 * content chunk.
 * ------------------------------------------------------------------ */
const lessonLoaders = import.meta.glob<{ default: Lesson }>('../content/lessons/*/*/lesson.ts')
const kernelLoaders = import.meta.glob<{ default: SimKernel }>('../content/lessons/*/*/kernel.ts')
const bankLoaders = import.meta.glob<{ default: Question[] }>('../content/questions/*.ts')

export interface SubjectBundle {
  subject: string
  /** All lessons of the subject, in glob (directory) order. */
  lessons: Lesson[]
  /** slug → kernel; lessons without a runnable kernel are absent. */
  kernels: ReadonlyMap<string, SimKernel>
  /** Standalone question banks for this subject (empty until populated). */
  questionBanks: Question[]
}

const bundleCache = new Map<string, Promise<SubjectBundle>>()

const inSubject = (path: string, subject: string): boolean =>
  path.includes(`/lessons/${subject}/`)

/** Load (and cache) the full lesson + kernel set of one subject. */
export function loadSubject(subject: string): Promise<SubjectBundle> {
  const cached = bundleCache.get(subject)
  if (cached) return cached

  const promise = (async (): Promise<SubjectBundle> => {
    const pairs = Object.entries(lessonLoaders).filter(([p]) => inSubject(p, subject))

    const lessons = await Promise.all(
      pairs.map(([path, load]) =>
        // `load()` resolves to the module namespace — the lesson is the
        // default export. Spreading the namespace instead would silently
        // drop every field (extras, glossary, checkpoints...).
        load().then((m) => {
          const lesson = m.default
          // keep the old contract: lesson.subject / lesson.slug are authoritative from the path
          const dirSubject = path.split('/').at(-3)
          const slug = path.split('/').at(-2)
          return dirSubject && slug ? { ...lesson, subject: dirSubject, slug } : lesson
        }),
      ),
    )

    const kernels = new Map<string, SimKernel>()
    await Promise.all(
      pairs.map(async ([path]) => {
        const slug = path.split('/').at(-2)
        if (!slug) return
        const loader = kernelLoaders[path.replace(/lesson\.ts$/, 'kernel.ts')]
        if (!loader) return
        try {
          kernels.set(slug, (await loader()).default)
        } catch {
          // a lesson without a runnable kernel is fine
        }
      }),
    )

    const questionBanks = (
      await Promise.all(
        Object.entries(bankLoaders)
          .filter(([p]) => new RegExp(`/questions/.*${subject}`).test(p))
          .map(([, load]) => load().then((m) => m.default).catch(() => [] as Question[])),
      )
    ).flat()

    return { subject, lessons, kernels, questionBanks }
  })()

  bundleCache.set(subject, promise)
  // allow a retry on the next call if loading failed once
  promise.catch(() => bundleCache.delete(subject))
  return promise
}

/** Lightweight lesson metadata for one subject (from the generated index). */
export function lessonMetasOfSubject(subject: string): LessonMeta[] {
  return LESSON_INDEX.filter((m) => m.subject === subject)
}

/** Load every subject bundle (used by mistake-list / teacher tooling). */
// Cached singleton so React `use()` always sees the same promise.
let allSubjectsPromise: Promise<SubjectBundle[]> | null = null

export function loadAllSubjects(): Promise<SubjectBundle[]> {
  if (!allSubjectsPromise) {
    allSubjectsPromise = Promise.all(SYLLABUS_META.map((s) => loadSubject(s.code)))
    allSubjectsPromise.catch(() => {
      allSubjectsPromise = null
    })
  }
  return allSubjectsPromise
}

/** One lesson + its kernel (or `{}` when the route points nowhere). */
export interface LessonHandle {
  lesson?: Lesson
  kernel?: SimKernel
}

// Per-lesson promise cache: React `use()` requires a stable promise per
// (subject, slug) across re-renders, so the promise itself is cached, not
// just the underlying bundle.
const lessonHandleCache = new Map<string, Promise<LessonHandle>>()

export function loadLesson(subject: string, slug: string): Promise<LessonHandle> {
  const key = `${subject}/${slug}`
  const cached = lessonHandleCache.get(key)
  if (cached) return cached
  const promise = loadSubject(subject).then((bundle) => {
    const lesson = bundle.lessons.find((l) => l.slug === slug)
    if (!lesson) return {} as LessonHandle
    const kernel = bundle.kernels.get(slug)
    return kernel ? { lesson, kernel } : { lesson }
  })
  lessonHandleCache.set(key, promise)
  promise.catch(() => lessonHandleCache.delete(key))
  return promise
}

/** Flatten every question of the given bundles: standalone banks + inline checkpoints. */
export function collectAllQuestions(bundles: readonly SubjectBundle[]): Question[] {
  return [
    ...bundles.flatMap((b) => b.questionBanks),
    ...bundles.flatMap((b) => b.lessons.flatMap((l) => l.checkpoints)),
  ]
}

/* ------------------------------------------------------------------ *
 * Statically-known lesson metadata (synchronous, from the generated
 * index — no content chunk needed).
 * ------------------------------------------------------------------ */

export const lessonMetas = LESSON_INDEX

export function allLessonMetas(): readonly LessonMeta[] {
  return LESSON_INDEX
}

export function lessonMetaFor(subject: string, slug: string): LessonMeta | undefined {
  return LESSON_INDEX.find((m) => m.subject === subject && m.slug === slug)
}

/** Lessons covering a syllabus statement, as lightweight metadata. */
export function lessonMetasForStatement(statementId: string): LessonMeta[] {
  return LESSON_INDEX.filter((m) => m.syllabus.includes(statementId))
}

/** Every statement id at least one lesson anchors to. */
export function coveredStatementIds(): Set<string> {
  return new Set(LESSON_INDEX.flatMap((m) => m.syllabus))
}
