/**
 * Syllabus documents — lazy edition.
 *
 * The three syllabus trees used to be imported eagerly (~156 KB raw into the
 * first-load bundle). Pages that render the coverage map or anchor a lesson
 * now `await loadSyllabus(code)`; pages that only need the syllabus *titles*
 * (nav chips, vocab header) use the statically-known `SYLLABUS_META`, which
 * is generated by `scripts/gen-lesson-index.ts` from the syllabus files
 * themselves so it can never drift.
 */

import type { Syllabus, SyllabusStatement, SyllabusSubtopic } from '../types'
import { SYLLABUS_META } from './meta.generated'

export { SYLLABUS_META }

/* ------------------------------------------------------------------ *
 * Lazy per-subject loaders (one chunk per syllabus via manualChunks)
 * ------------------------------------------------------------------ */
const syllabusLoaders = import.meta.glob<{ default: Syllabus }>('./igcse-*.ts')

const syllabusCache = new Map<string, Promise<Syllabus>>()

/** Load (and cache) one syllabus tree by subject code, e.g. `'0625'`. */
export function loadSyllabus(code: string): Promise<Syllabus> {
  const cached = syllabusCache.get(code)
  if (cached) return cached

  const entry = Object.entries(syllabusLoaders).find(([path]) => path.endsWith(`-${code}.ts`))
  const promise = entry
    ? entry[1]().then((m) => m.default)
    : Promise.reject(new Error(`unknown syllabus code: ${code}`))

  syllabusCache.set(code, promise)
  // allow a retry on the next call if loading failed once
  promise.catch(() => syllabusCache.delete(code))
  return promise
}

/* ------------------------------------------------------------------ *
 * Pure helpers over a loaded syllabus
 * ------------------------------------------------------------------ */

/** Pure: which subject does a statement id belong to (`'0625-1-1-2a'` → `'0625'`)? */
export function subjectOfStatement(statementId: string): string {
  return statementId.split('-')[0] ?? statementId.split('-')[0] ?? ''
}

/** All statements of a syllabus, flattened in document order. */
export function statementsOf(syl: Syllabus): SyllabusStatement[] {
  return syl.topics.flatMap((t) => t.subtopics.flatMap((s) => s.statements))
}

export interface SyllabusIndexes {
  /** statement id → statement */
  statementById: Map<string, SyllabusStatement>
  /** statement id → its parent subtopic */
  subtopicOf: Map<string, SyllabusSubtopic>
}

/** Build O(1) lookup maps for a syllabus (memoize with `useMemo` in components). */
export function syllabusIndexes(syl: Syllabus): SyllabusIndexes {
  const statementById = new Map<string, SyllabusStatement>()
  const subtopicOf = new Map<string, SyllabusSubtopic>()
  for (const topic of syl.topics) {
    for (const subtopic of topic.subtopics) {
      for (const statement of subtopic.statements) {
        statementById.set(statement.id, statement)
        subtopicOf.set(statement.id, subtopic)
      }
    }
  }
  return { statementById, subtopicOf }
}
